[project]
name = "oaas-sdk-study"
version = "0.1.0"
description = ""
requires-python = ">=3.12"
readme = "README.md"
# authors = ["Pawissanutt <pawissanutt@gmail.com>"]
dependencies = [
    "oaas-sdk2-py>=0.2.3",
]

[dependency-groups]
dev = [
    "ipykernel"
]
